### ISSUE TITLE
p2p code review 02 07 2020

### ISSUE THREAD

**Issue by dili021** [dili021/responsive-design#2]
Comments & suggestions are welcome!

**Comment by nyatindopatrick** [comment]
Good work! I think these suggestions can help improve the responsiveness:

- at smaller screen set the "grid4-item1" max-width to 100%
```
@media (max-width: 768px)
.grid4-item1 {
    flex: 80%;
    max-width: 100%;
}
```

- In the mobile view you can set the footer-bottom width to 80% to avoid the overflow.

I just have those few remarks. Cheers!

**Comment by patriciachrysy** [comment]
Good job @dili021!! Nevertheless, there are some broken things on your responsive views:
- on max-width: 1023px, your sub-item-image div which contains the text and the image is of the wrong height. The image exceeds the bounds of the div, and the div itself is supposed to have a light pink background
- on the max-width: 767px, your grid4-item1 div is supposed to take the whole width of the screen with some small margin on left and right
- The navbar disappears on this same screen size too

**Comment by dili021** [comment]
Thanks for the input, I will go make Maria proud!
